services:
  go2_stair_climber:
    build:
      context: .
      dockerfile: Dockerfile
    image: go2_stair_climber:humble
    container_name: tash_team1_go2_stair_climber
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ../ros2_ws/src:/workspace/go2-stair-climber/ros2_ws/src
      - /dev:/dev
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
    command: bash