<?xml version="1.0"?>
<package format="3">
  <name>person_detector</name>
  <version>0.0.0</version>
  <description>YOLOv8 person detection from D435i camera</description>
  <maintainer email="jen@example.com">jen</maintainer>
  <license>Apache-2.0</license>
  
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
